name: Deployment - Test
on:
  push:
    branches:
      - deployment-test
  pull_request:
    branches:
      - deployment-test


env:
  HOST: mephisto.dlab-mephisto.com
  USERNAME: deployer
  PORT: 22
  MTURK_NAME: my_mturk_user_sandbox
  MTURK_TYPE: mturk_sandbox
  USER_EMAIL: jaythaiduong.huynh@uq.edu.au
  USER_NAME: jaythaiduong.huynh
  REPO_DIR: ~/${{ github.event.repository.name }}-${{ github.ref_name }}
  APP_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
  APP_ENV: test
  AWS_REGION: ap-southeast-2
  SVLD_VERSION: alpha-2
  PREVIEW_URL_PREFIX: '%Mock task launched.* for preview%'
  CONT_PORT: 3000

jobs:
  build-container:
    name: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Authorize AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get secrets from Prod SSM Parameter Store
        uses: cngthnh/aws-ssm-getparameters-action@v7
        if: ${{ env.APP_ENV == 'prod' }}
        with:
            parameterPairs: "HOSTED_ZONE_ID=HOSTED_ZONE_ID,VPC_ID=VPC_ID,DOMAIN=DOMAIN,ECR_IMAGE_REPO=ECR_IMAGE_REPO,ACCOUNT_ID=AWS_ACCOUNT_ID,MTURK_ACCESS_KEY_ID=MTURK_ACCESS_KEY_ID,MTURK_SECRET_ACCESS_KEY=MTURK_SECRET_ACCESS_KEY,PROLIFIC_API_KEY_PROD=PROLIFIC_API_KEY,DOTNETRC=DOTNETRC,HEROKU_API_KEY=HEROKU_API_KEY,PRIVATE_KEY=PRIVATE_KEY"
            withDecryption: "true" # defaults to true
            
      - name: Get secrets from Test SSM Parameter Store
        uses: cngthnh/aws-ssm-getparameters-action@v7
        if: ${{ env.APP_ENV == 'test' || env.APP_ENV == 'dev' }}
        with:
            parameterPairs: "HOSTED_ZONE_ID=HOSTED_ZONE_ID,VPC_ID=VPC_ID,DOMAIN=DOMAIN,ECR_IMAGE_REPO=ECR_IMAGE_REPO,ACCOUNT_ID=AWS_ACCOUNT_ID,MTURK_ACCESS_KEY_ID=MTURK_ACCESS_KEY_ID,MTURK_SECRET_ACCESS_KEY=MTURK_SECRET_ACCESS_KEY,PROLIFIC_API_KEY_TEST=PROLIFIC_API_KEY,DOTNETRC=DOTNETRC,HEROKU_API_KEY=HEROKU_API_KEY,PRIVATE_KEY=PRIVATE_KEY"
            withDecryption: "true" # defaults to true

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Build and publish image into ECR, then start the service
        uses: cngthnh/serverless-mephisto@alpha-2
